#!/usr/bin/env bash
set -e

###############################################################################
# TrueNAS SCALE udev and systemd setup for automatic backup on drive insertion
# Automated version for use in TrueNAS init tasks
#
# This script creates udev rules to automatically trigger backups when 
# drives are inserted. It should be run at boot time via a TrueNAS init task.
#
# Usage: As a TrueNAS SCALE init task
###############################################################################

# Get the real directory where the script is located (resolving symlinks)
SCRIPT_PATH=$(readlink -f "$0" 2>/dev/null || readlink "$0" 2>/dev/null || echo "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
# Make sure SCRIPT_DIR is absolute
if [[ ! "$SCRIPT_DIR" = /* ]]; then
    SCRIPT_DIR="$(pwd)/$SCRIPT_DIR"
fi

# Backup script paths
BACKUP_SCRIPT="$SCRIPT_DIR/backup.sh"
WRAPPER_SCRIPT="$SCRIPT_DIR/backup_wrapper.sh"

# Log file path
LOG_FILE="${SCRIPT_DIR}/setup_udev_auto.log"

# udev rules directory
UDEV_RULES_DIR="/etc/udev/rules.d"
UDEV_RULE_FILE="$UDEV_RULES_DIR/99-backup-drive.rules"

# systemd service directory and file
SYSTEMD_DIR="/etc/systemd/system"
SYSTEMD_SERVICE="zfs-backup.service"
SYSTEMD_SERVICE_FILE="$SYSTEMD_DIR/$SYSTEMD_SERVICE"

# Initialize log file
> "$LOG_FILE"

# Function to log messages to file
log() {
    local timestamp
    timestamp=$(date '+%F %T')
    echo "$timestamp [INFO] $1" >> "$LOG_FILE"
}

# Log errors to file
log_error() {
    local timestamp
    timestamp=$(date '+%F %T')
    echo "$timestamp [ERROR] $1" >> "$LOG_FILE"
}

# Check if script is run with sudo/root privileges
if [ "$(id -u)" -ne 0 ]; then
    log_error "This script must be run with sudo privileges."
    exit 1
fi

# Check if backup script exists
if [ ! -f "$BACKUP_SCRIPT" ]; then
    log_error "Backup script not found at $BACKUP_SCRIPT"
    exit 1
fi

# Make sure backup script and wrapper script are executable
chmod +x "$BACKUP_SCRIPT"
chmod +x "$WRAPPER_SCRIPT"

log "Starting setup of automated backup for TrueNAS SCALE"

# Create systemd service for backup script
log "Creating systemd service at $SYSTEMD_SERVICE_FILE"

# Check if service already exists, stop it first if it does
if systemctl --quiet is-active "$SYSTEMD_SERVICE" 2>/dev/null; then
    log "Stopping existing $SYSTEMD_SERVICE service"
    systemctl stop "$SYSTEMD_SERVICE" 2>> "$LOG_FILE" || log "Failed to stop existing service"
fi

# Create the service file
cat > "$SYSTEMD_SERVICE_FILE" << EOF
[Unit]
Description=ZFS Backup on Drive Insert
After=network.target

[Service]
Type=simple
ExecStart=$WRAPPER_SCRIPT
StandardOutput=journal
StandardError=journal
User=root
Group=root
TimeoutStartSec=0
EOF

# Reload systemd daemon
log "Reloading systemd daemon"
systemctl daemon-reload 2>> "$LOG_FILE"

log "Systemd service created: $SYSTEMD_SERVICE"

# Create udev rules
log "Creating generic udev rule for drive insertion"

# Create rules directory if it doesn't exist
mkdir -p "$UDEV_RULES_DIR"

# Create or truncate the rules file
> "$UDEV_RULE_FILE"

# Add header to rules file
cat > "$UDEV_RULE_FILE" << EOF
# Automatically generated by setup_udev_auto.sh
# DO NOT EDIT - This file will be overwritten on system boot
# Generated on: $(date)
#
# udev rule for triggering automatic backups when any disk drive is inserted
EOF

# Add a generic rule for all block devices
echo "" >> "$UDEV_RULE_FILE"
echo "# Generic rule to trigger backup script on any drive insertion" >> "$UDEV_RULE_FILE"
echo "ACTION==\"add\", SUBSYSTEM==\"block\", ENV{DEVTYPE}==\"disk\", ENV{MAJOR}!=\"1\", RUN+=\"/bin/systemctl start $SYSTEMD_SERVICE\"" >> "$UDEV_RULE_FILE"

log "udev rule created at $UDEV_RULE_FILE"

# Reload udev rules
log "Reloading udev rules"
udevadm control --reload-rules 2>> "$LOG_FILE"
log "udev rules reloaded successfully"

log "Setup completed successfully"
log "Automatic backups will now be triggered when any drive is inserted"
log "The wrapper script will check if the disk serial matches before executing the backup"
log "To check logs, see:"
log "  - Setup logs: $LOG_FILE"
log "  - Wrapper logs: $SCRIPT_DIR/backup_wrapper.log"
log "  - Systemd service logs: 'journalctl -u $SYSTEMD_SERVICE'"

exit 0
